Repository googleapis/java-bigtable-hbase, pull requests merged in 2019-12, with the labels that each got.

#2292 chore(deps): update renovate config
  renovate.json
Labels: cla: yes

#2288 docs: Updated readme to redirect user to veneer client
  README.md
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/config/BigtableOptions.java
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java
Labels: cla: yes

#2266 [Part-1] Adding Integration test cases for Table API
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestBatch.java
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestPut.java
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/TestBufferedMutator.java
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/TestPutGetDelete.java
  bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/AbstractBigtableTable.java
  bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BatchExecutor.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestBatch.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableTable.java
Labels: cla: yes

#2295 build: add kokoro configs for presubmit tests
  .kokoro/build.bat
  .kokoro/build.sh
  .kokoro/coerce_logs.sh
  .kokoro/common.cfg
  .kokoro/dependencies.sh
  .kokoro/linkage-monitor.sh
  .kokoro/presubmit/clirr.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/dependencies.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/java11.cfg
  .kokoro/presubmit/java8-osx.cfg
  .kokoro/presubmit/java8-win.cfg
  .kokoro/presubmit/java8.cfg
  .kokoro/presubmit/linkage-monitor.cfg
  .kokoro/presubmit/lint.cfg
  .kokoro/trampoline.sh
Labels: cla: yes

#2298 build: fix unit test kokoro builds
  .kokoro/build.sh
Labels: cla: yes

#2301 build: fix IT tests
  .kokoro/build.sh
  .kokoro/presubmit/integration.cfg
Labels: cla: yes

#2302 build: add in more IT tests
  .kokoro/build.sh
  .kokoro/presubmit/integration.cfg
Labels: cla: yes

#2285 test: Fix for Gaps b/w HBase and Bigtable Admin API
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestListTables.java
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/TestAdminOps.java
  bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/IntegrationTests.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/IntegrationTests.java
Labels: cla: yes, needs work

#2289 test: updates snapshot operation with sanitary checks
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestSnapshot.java
  bigtable-client-core-parent/bigtable-hbase/src/main/java/org/apache/hadoop/hbase/client/AbstractBigtableAdmin.java
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestSnapshots.java
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/src/main/java/com/google/cloud/bigtable/hbase1_x/BigtableAdmin.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestSnapshots.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/async/TestAsyncSnapshots.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableAdmin.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableAsyncAdmin.java
Labels: cla: yes, needs work

#2304 chore: Prepare to cleanup channel management
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java
Labels: cla: yes, type: cleanup

#2303 chore: cleanup connection initialization
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableClusterUtilities.java
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java
Labels: cla: yes

#2305 deps: fix dependency build
  .kokoro/dependencies.sh
  bigtable-client-core-parent/bigtable-client-core/pom.xml
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/pom.xml
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/TestScan.java
  bigtable-client-core-parent/bigtable-hbase/pom.xml
  bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/PutAdapterPerf.java
  bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/RowMergerPerf.java
  bigtable-dataflow-parent/bigtable-beam-import/pom.xml
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/TemplateUtils.java
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/ExportJob.java
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/HBaseResultToMutationFn.java
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/ImportJob.java
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/Main.java
  bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/SequenceFileSource.java
  bigtable-dataflow-parent/bigtable-beam-import/src/test/java/com/google/cloud/bigtable/beam/it/CloudBigtableBeamITTest.java
  bigtable-dataflow-parent/bigtable-hbase-beam/pom.xml
  bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/batch/common/CloudBigtableService.java
  bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/batch/common/CloudBigtableServiceImpl.java
  bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableIO.java
  bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableScanConfiguration.java
  bigtable-dataflow-parent/bigtable-hbase-beam/src/main/java/com/google/cloud/bigtable/beam/CloudBigtableTableConfiguration.java
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-hadoop/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-mapreduce/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/src/test/java/com/google/cloud/bigtable/hbase/TestBigtableConnection.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-hadoop/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/test/java/com/google/cloud/bigtable/hbase/TestBigtableConnection.java
  pom.xml
Labels: cla: yes

#2308 deps: fix hbaseLocalMiniClusterTestH2 tests
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-hadoop/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-hadoop/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/async/AbstractAsyncTest.java
  pom.xml
Labels: cla: yes

#2315 chore: update renovate config
  renovate.json
Labels: cla: yes

#2327 chore: clean up pom
  pom.xml
Labels: cla: yes

#2329 chore(deps): group core dependencies
  renovate.json
Labels: cla: yes
