Repository googleapis/java-bigtable-hbase, pull requests merged in 2020-09, with the labels that each got.

#2626 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#2628 fix: ZeroCopyByteStringUtil can return incorrect results in some cases
  bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/util/ZeroCopyByteStringUtil.java
  bigtable-client-core-parent/bigtable-hbase/src/test/java/com/google/cloud/bigtable/hbase/util/ZeroCopyByteStringUtilTest.java
Labels: cla: yes

#2630 deps: update bigtable veneer to 1.15.0
  bigtable-client-core-parent/bigtable-client-core/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  pom.xml
Labels: api: bigtable, cla: yes

#2632 chore: add repo settings config
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#2633 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
