Repository googleapis/java-bigtable-hbase, pull requests merged in 2020-10, with the labels that each got.

#2640 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#2644 chore(test): fix typo
  bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/TestAppProfile.java
Labels: automerge, cla: yes

#2645 chore(test): fix typo
  bigtable-client-core-parent/bigtable-client-core/src/test/java/com/google/cloud/bigtable/grpc/TestAppProfile.java
Labels: cla: yes

#2649 test(deps): update junit to 4.13.1
  pom.xml
Labels: api: bigtable, cla: yes

#2653 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#2651 test(deps): update jmh to 1.26
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-benchmarks/clirr-ignored-differences.xml
  pom.xml
Labels: api: bigtable, cla: yes

#2663 chore: regenerate common templates
  .github/CODEOWNERS
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: partial

#2664 chore: update synth configs
  .github/CODEOWNERS
  .github/snippet-bot.yml
  .repo-metadata.json
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#2665 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: cla: yes, context: full

#2635 deps: update shared config to 0.9.2
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-mapreduce/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-hadoop/pom.xml
  pom.xml
Labels: api: bigtable, cla: yes

#2565 test: Remove unused assertions and deprecated methods from HBase2
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestColumnFamilyAdmin.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestCreateTableHBase2.java
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/src/test/java/com/google/cloud/bigtable/hbase/TestPut.java
Labels: api: bigtable, cla: yes

#2667 chore(docs): update docs
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#2671 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
