Repository googleapis/java-bigtable-hbase, pull requests merged in 2020-11, with the labels that each got.

#2676 chore: disable travis
  .travis.yml
  README.md
  travis.sh
Labels: api: bigtable, automerge, cla: yes

#2678 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#2684 fix: qualifier filter comparators
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/src/test/java/com/google/cloud/bigtable/hbase/AbstractTestFilters.java
  bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/filters/QualifierFilterAdapter.java
Labels: api: bigtable, automerge, cla: yes

#2683 feat: feat: Add keepalive in grpc channelbuilder #2682 in bigtable-1.x
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java
Labels: api: bigtable, cla: yes

#2680 feat: Enabling OpenCensus publishing for HBase shaded clients
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
Labels: api: bigtable, cla: yes

#2686 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: bigtable, cla: yes, context: full

#2682 feat: Add keepalive in grpc channelbuilder
  bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/BigtableSession.java
Labels: api: bigtable, cla: yes

#2679 feat: Enabling OpenCensus publishing for HBase shaded clients (onto bigtable-1.x branch)
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
Labels: api: bigtable, cla: yes

#2698 chore: disable travis (#2676)
  .travis.yml
  README.md
  travis.sh
Labels: api: bigtable, cla: yes

#2699 build: update distributionManagement in parent pom (#2470)
  pom.xml
Labels: automerge, cla: yes

#2701 deps: update mockito to 3.6.0
  pom.xml
Labels: api: bigtable, cla: yes

#2704 chore: Release cloud-bigtable-client v1.17.1
  bigtable-client-core-parent/bigtable-client-core/pom.xml
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/pom.xml
  bigtable-client-core-parent/bigtable-hbase/pom.xml
  bigtable-client-core-parent/pom.xml
  bigtable-dataflow-parent/bigtable-beam-import/pom.xml
  bigtable-dataflow-parent/bigtable-hbase-beam/pom.xml
  bigtable-dataflow-parent/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-benchmarks/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-hadoop/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-mapreduce/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/pom.xml
  bigtable-hbase-1.x-parent/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-hadoop/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/pom.xml
  bigtable-hbase-2.x-parent/pom.xml
  bigtable-test/bigtable-emulator-maven-plugin/pom.xml
  bigtable-test/pom.xml
  pom.xml
  versions.txt
Labels: api: bigtable, cla: yes

#2714 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full

#2715 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: bigtable, automerge, cla: yes, context: full, samples
