Repository googleapis/java-bigtable-hbase, pull requests merged in 2020-06, with the labels that each got.

#2541 chore: add exclusions to synth.py
  synth.py
Labels: cla: yes

#2542 docs: update CONTRIBUTING.md to include code formatting (#534)
  CONTRIBUTING.md
  synth.metadata
Labels: cla: yes, context: full

#2545 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#2546 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#2552 ci: switch to secret manager for samples/integration tests
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#2554 ci: update integration configs
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/presubmit/integration.cfg
Labels: cla: yes

#2558 ci: update snapshot IT config
  .kokoro/nightly/integration-snapshot.cfg
Labels: cla: yes
