Repository googleapis/java-bigtable-hbase, pull requests merged in 2022-04, with the labels that each got.

#3572 fix: minor documentation update
  hbase-migration-tools/bigtable-hbase-replication/README.md
  hbase-migration-tools/bigtable-hbase-replication/bigtable-hbase-replication-core/src/main/java/com/google/cloud/bigtable/hbase/replication/configuration/HBaseToCloudBigtableReplicationConfiguration.java
Labels: automerge

#3575 fix: use instance/project URI in log
  hbase-migration-tools/bigtable-hbase-replication/bigtable-hbase-replication-core/src/main/java/com/google/cloud/bigtable/hbase/replication/CloudBigtableReplicator.java
Labels: api: bigtable

#3579 test: enable the ability to skip unit tests, while running integration tests
  pom.xml
Labels: api: bigtable

#3582 deps: upgrade guava to 31.1-jre and Bigtable to 2.6.2
  pom.xml
Labels: api: bigtable, automerge, size: xs

#3587 build: skip clirr for replication modules as temporary workaround
  hbase-migration-tools/bigtable-hbase-replication/bigtable-hbase-1.x-replication/pom.xml
  hbase-migration-tools/bigtable-hbase-replication/bigtable-hbase-2.x-replication/pom.xml
Labels: api: bigtable, automerge, size: s

#3593 feat: next release from main branch is 2.2.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigtable, automerge, size: s
