Repository googleapis/java-bigtable-hbase, pull requests merged in 2023-02, with the labels that each got.

#3944 deps: replace all transitive log4j deps with reload4j for 2.1.x
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/pom.xml
  bigtable-client-core-parent/bigtable-hbase/pom.xml
  bigtable-dataflow-parent/bigtable-beam-import/pom.xml
  bigtable-dataflow-parent/bigtable-hbase-beam/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-benchmarks/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-hadoop/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/pom.xml
  bigtable-test/bigtable-emulator-maven-plugin/pom.xml
  pom.xml
Labels: api: bigtable, size: m

#3945 deps: replace all transitive log4j deps with reload4j for 2.6.x
  bigtable-client-core-parent/bigtable-hbase-integration-tests-common/pom.xml
  bigtable-client-core-parent/bigtable-hbase/pom.xml
  bigtable-dataflow-parent/bigtable-beam-import/pom.xml
  bigtable-dataflow-parent/bigtable-hbase-beam/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-benchmarks/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-hadoop/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-integration-tests/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x-shaded/pom.xml
  bigtable-hbase-1.x-parent/bigtable-hbase-1.x/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-integration-tests/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x-shaded/pom.xml
  bigtable-hbase-2.x-parent/bigtable-hbase-2.x/pom.xml
  bigtable-test/bigtable-emulator-maven-plugin/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-hadoop/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-integration-tests/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-1.x-parent/bigtable-hbase-mirroring-client-1.x-shaded/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x-hadoop/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-2.x-parent/bigtable-hbase-mirroring-client-2.x/pom.xml
  hbase-migration-tools/mirroring-client/bigtable-hbase-mirroring-client-core-parent/bigtable-hbase-mirroring-client-core/pom.xml
  pom.xml
Labels: api: bigtable, size: m

#3960 chore: fix published dependencies of bigtable-beam-import
  .github/sync-repo-settings.yaml
  .kokoro/dependencies.sh
  pom.xml
  renovate.json5
Labels: api: bigtable, size: s

#3966 chore(main): temporarily disable Clirr Binary Compatibility test for 2.1.x branch
  .github/sync-repo-settings.yaml
Labels: api: bigtable, size: xs

#3975 build: skip clirr for release build of 2.1.x
  .kokoro/release/stage.sh
  owlbot.py
Labels: api: bigtable, size: xs

#3970 chore(main): Re-Enable Binary Compatibility test for 2.1.x branch
  .github/sync-repo-settings.yaml
Labels: api: bigtable, size: xs

#3985 fix(deps): re-add reload4j as a dependency in bigtable-hbase-beam
  bigtable-dataflow-parent/bigtable-hbase-beam/pom.xml
Labels: api: bigtable, automerge, size: s
